alura:
  database:
    url: jdbc:postgresql://localhost:5432/alurabank
    user: postgres
    password: postgres
  keycloak:
    url: http://localhost:8080/realms/alura


spring:
  datasource:
    url: ${DATABASE_URL:${alura.database.url}}
    username: ${DATABASE_USER:${alura.database.user}}
    password: ${DATABASE_PASSWORD:${alura.database.password}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL:${alura.keycloak.url}}
          jwk-set-uri: ${KEYCLOAK_REALM_URL:${alura.keycloak.url}}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    oauth:
      client-id: app
      scopes: openid
      use-pkce-with-authorization-code-grant: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:13.2:////aluratest
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
