
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alurabank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/test-oauth
          jwk-set-uri: http://localhost:8180/realms/test-oauth/protocol/openid-connect/certs
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/alurabanktest
  jpa:
    hibernate:
      ddl-auto: create-drop
