
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alurabank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/alurabanktest
  jpa:
    hibernate:
      ddl-auto: create-drop
