version: '3.7'

services:
  curl:
    image: ubuntu-curl
    command:
      - "curl"
      - "http://python:8080"
    depends_on:
      - python
  python:
    image: ubuntu-python
    working_dir: "/site"
    command:
      - "/usr/bin/python3"
      - "-m"
      - "http.server"
      - "8080"
    ports:
      - "8000:8080"
