version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alurabank
    ports:
      - "5432:5432"
    volumes:
      - "./data/:/var/lib/postgresql/data"
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    command:
      - "start-dev"
      - "--http-port=8081"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"


