version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alurabank
    ports:
      - "5432:5432"
    volumes:
      - "storage:/var/lib/postgresql/data"
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
  bank:
    image: alura/bank
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/alurabank
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      KEYCLOAK_REALM_URL: http://keycloak:8080/realms/alura
    depends_on:
      - db
      - keycloak
    ports:
      - "8080:8080"



volumes:
  storage:
